### ISSUE TITLE
Can't update a --indeterminate progressbar window

### ISSUE THREAD

**Issue by lmarceg** [mstratman/cocoadialog#50]
I am using this simple script to generate an indeteminate progressbar window:

mkfifo /tmp/hpipe2
/usr/bin/CocoaDialog.app/Contents/MacOS/CocoaDialog progressbar \
--indeterminate --float --title "Rotazione video" \
--posX "center" --posY 300 --text "Attendere..." < /tmp/hpipe2 &
exec 4<> /tmp/hpipe2

Now, whenever I type

echo "something" >&4
echo something >&4
echo -n something >&4

nothing will happen. The messages still stays the same, "Attendere", which is the initial text.

If I use the --percent feature instead of the --progressbar and type

echo "28 the percentage is 28%" >&4

everything will work fine immediately.
Any idea on how to fix this?

i am using 3.0.0beta5

**Comment by Caperr** [comment]
You need to send your text to the name of your pipe (or however you're supposed to say that, I'm new :P).

I ran into this problem my self just now, instead of typing
echo "something" >&4
type
echo "something" > /tmp/hpipe2

It's the same when trying to change the percentage of progress bars:
you can type echo 20 > /tmp/hpipe2 to change the progress to 20%

**Comment by lmarceg** [comment]
Very good hint indeed!!!
Thanks

**Comment by Caperr** [comment]
No problem, only wish I'd seen this post sooner!
