### ISSUE TITLE
Have no default button

### ISSUE THREAD

**Issue by ctangora** [mstratman/cocoadialog#59]
Have a way to have the msgbox and it's cousins have no default button selected.  

Issue running into when people are typing on e-mail, etc, and they hit return or space as the window comes up.  Because there is a default option it gets automatically chosen.  Having no default option would make them choose with the mouse/cursor only.

I know it's a strange request, but I was thinking as an option like --no-default.  Not the standard behavior.

**Comment by quinncomendant** [comment]
+1 for this. We're using CocoaDialog in a situation where we must prompt the user to allow a sensitive action. In our current use, we're already experiencing users accidentally approving the action.

**Comment by markcarver** [comment]
Considering that this would be an explicit opt-in, I don't see why this should not be added.

There are use cases where you don't want a default action because each action has equal weight or that is a specific a negative, neutral or positive connotation to the question being asked that requires what the user deems as "default", not the app.

I'd say let's add a new `--no-default-button` option for this.
