### ISSUE TITLE
Is this project in maintenance only mode

### ISSUE THREAD

**Issue by scottfwalter** [mstratman/cocoadialog#66]
I noticed there hasn't been any activity in a couple years.  Just curious if there will be any future development?

**Comment by mralexgray** [comment]
any interest in starting the conversation back up on gitter.im?  it seems like the spiritual successor to IRC, but with more PUSH! :-)  i created a room.. @markcarver , unfortunately it's under my name..  maybe we should set up an "organization"?  not sure how that works.  but you can check it out at https://gitter.im/mralexgray/cocoadialog# and let me know your thoughts about how best to approach it.. or if you're dead set on IRC, that's always a safe, if slightly anachronistic way of doing it.  :-)

**Comment by markcarver** [comment]
I've actually never heard of that service until just now. Hm, interesting.

Personally, I'd prefer IRC as I am always on there (ZNC) and because I already have the necessary GUIs since it's my primary communication medium for work (not specifically this project).

I'm also perhaps becoming more anti-PUSH because when I'm done with work, I typically like to keep it that way :smile:

I get email notifications for GH issues though and will review them when I can.

---

That all being said, I'm certainly not opposed to something like https://gitter.im. Especially if this becomes more of an "organizational" effort (which @mstratman would have to change, I don't have the necessary perms to do that).

**Comment by mralexgray** [comment]
what you're talking about is one of the hardest boundaries to delineate in the world of git(hub). When does _I become we_.. and how do we make that work for everyone...

**Comment by mm2270** [comment]
I also would love to help contribute to this project to help keep it alive in any way I can. I don't know software development, but I can possibly help with documentation. I've become a pseudo expert of a sorts with the 3.0 beta versions and its various controls and extra options.

**Comment by markcarver** [comment]
FWIW, Gitter.im started a new beta IRC API bridge (https://irc.gitter.im), so I've joined the room mentioned above until something else comes along I guess.

**Comment by Darkomen78** [comment]
We need #CocoaDialog on Slack ;-) https://macadmins.slack.com

**Comment by markcarver** [comment]
I've created the https://cocoadialog.slack.com workspace. Working on getting an automated invitation system up, but for now you can use this link (expires in 30 days):

https://join.slack.com/t/cocoadialog/shared_invite/enQtMjU2MTMyMDgwOTk2LTA1NjQ1MWMzMzk0ZWE5NmZiNGRiNDk4ZGFhODQzZmNmMDM2NjcyNDk5YWMxNmY4ODliNjY3M2Y1M2QzN2RjYjA

**Comment by markcarver** [comment]
https://slack.cocoadialog.com now exists and can send users invitations.

https://cocoadialog.com now has a Slack button at the bottom that inlines the above site when clicked.
