### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by patgmac** [mstratman/cocoadialog#95]
Not much action in a while. Just checking in case we need to move to osascript 😡

**Comment by markcarver** [comment]
Yes, albeit fairly slow lately (summer).

I honestly didn't realize how much time has passed since I last worked on this.

However, considering that I'm the only one actually contributing to it lately or working on it, it's not really all that surprising.

The squeaky wheel gets the grease and my time has been allocated elsewhere to work and other FOSS projects.

If you wish to create new issues, I'll do my best to be as responsive as possible.

I know it's been a few days since you created this one, but right now I can only really promise my weekends to this project.
